dbesite/awards/urls.py
from django.urls import path

from . import views

app_name = 'awards'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('award/<int:pk>', views.AwardDetailView.as_view(), name='award_detail'),
    path('award/<int:award_id>/vote', views.vote, name='award_vote'),
    path('award/add', views.addAward, name='award_add'),
    path('api/awardshow', views.AwardShowViewSet.as_view(), name='award_api_awardshow'),
]

dbesite/dbesite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('awards/', include('awards.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'), # new
]

dbesite/awards/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class AwardShow(models.Model):
    award_show_title = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.award_show_title

    def save(self, *args, **kwargs):
        if self.is_active:
            if not self.pk:  # object is being created, thus no primary key field yet
                AwardShow.objects.all().update(is_active=False)
            else:
                AwardShow.objects.all().exclude(pk=self.pk).update(is_active=False)

        super(AwardShow, self).save(*args, **kwargs)

class Award(models.Model):
    award_name = models.CharField(max_length=50)
    award_show = models.ForeignKey(AwardShow, on_delete=models.CASCADE, null=True)
    index = models.IntegerField(default=0)

    def __str__(self):
        return self.award_name

    def save(self, *args, **kwargs):
        if not self.pk:  # object is being created, thus no primary key field yet
            if self.award_show is None:
                self.award_show = AwardShow.objects.get(is_active=True)
            if not self.index:
                self.index = Award.objects.filter(award_show=self.award_show).count() + 1

        super(Award, self).save(*args, **kwargs)

        other_awards_at_same_index = Award.objects.filter(award_show=self.award_show, index=self.index)
        if other_awards_at_same_index.count() > 1:
            for other_award in other_awards_at_same_index.exclude(pk=self.pk):
                for x in range(1, Award.objects.filter(award_show=self.award_show).count() + 1):
                    if Award.objects.filter(award_show=self.award_show, index=x).count() == 0:
                        other_award.index = x
                        other_award.save()
                        break

class Winner(models.Model):
    award = models.ForeignKey(Award, on_delete=models.CASCADE)
    voter = models.ForeignKey(User, on_delete=models.CASCADE)
    winner_text = models.CharField(max_length=200)
    link = models.CharField(max_length=200, default='#')

    def __str__(self):
        return self.winner_text

    def save(self, *args, **kwargs):
        super(Winner, self).save(*args, **kwargs)
        if Winner.objects.filter(award=self.award, voter=self.voter).count() > 1:
            Winner.objects.filter(award=self.award, voter=self.voter).exclude(pk=self.pk).delete()

dbesite/awards/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from rest_framework import generics

from .models import Award, AwardShow, Winner
from .serializers import AwardSerializer, AwardShowSerializer, WinnerSerializer

class AwardShowViewSet(generics.ListAPIView):
    """
    API endpoint that allows all awards in the active awardshow to be viewed.
    """
    queryset = AwardShow.objects.all()
    serializer_class = AwardShowSerializer

class IndexView(generic.ListView):
    template_name = 'awards/index.html'
    context_object_name = 'awards_list'

    def get_queryset(self):
        """Returns all awards for the active award show."""
        active_award_show = get_object_or_404(AwardShow, is_active=True) 
        return Award.objects.filter(award_show=active_award_show).order_by('index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['user_voted_awards'] = context['awards_list'].filter(winner__voter=self.request.user)

        return context

class AwardDetailView(generic.DetailView):
    model = Award
    template_name = 'awards/detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        current_user = self.request.user
        try:
            context['current_winner'] = context['award'].winner_set.get(voter=current_user)
        except Winner.DoesNotExist:
            context['current_winner'] = None

        return context

def vote(request, award_id):
    if (not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('login'))

    award = get_object_or_404(Award, pk=award_id)
    if (request.POST['winner_name'] == ''):
        return render(request, 'awards:award_detail', {
            'award': award,
            'error_message': "You didn't enter a winner.",
        })

    new_winner = Winner(winner_text=request.POST['winner_name'], award=award, voter=request.user, link=request.POST['winner_link'])
    new_winner.save()

    return HttpResponseRedirect(reverse('awards:index'))

def addAward(request):
    if (not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('login'))

    if (request.POST['award_name'] == ''):
        return render(request, 'awards:index', {
            'error_message': "You didn't enter a title.",
        })
    
    new_award = Award(award_name=request.POST['award_name'])
    new_award.save()

    return HttpResponseRedirect(reverse('awards:index'))

dbesite/awards/templates/awards/detail.html
<style>
    input[type=text] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;
    border: 2px solid black;
    border-radius: 4px;
  }

  input[type=text]:focus {
    border: 3px solid #555;
  }

  input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 20px;
  border: none;
  border-radius: 4px;
  margin-top: 20px;
  cursor: pointer;
  float: right;
}

input[type=submit]:hover {
  background-color: #45a049;
}

label {
  padding: 12px 12px 12px 0;
  display: inline-block;
}
</style>
<form action="{% url 'awards:award_vote' award.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ award.award_name }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% if current_winner %}<p><strong>You have currently nominated: {{ current_winner.winner_text }}</strong></p>{% endif %}

        <label for="winner_name">Your winner:</label><br>
        <input type="text" name="winner_name" id="winner_name" length="100" autocomplete="off" required />
        <label for="winner_name">Evidence (Youtube Link?)</label><br>
        <input type="text" name="winner_link" id="winner_link" autocomplete="off" />
    </fieldset>
    <input type="submit" value="Vote">
</form>

dbesite/awards/templates/awards/index.html
<style>
    input[type=text] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;
    border: 2px solid black;
    border-radius: 4px;
  }

  input[type=text]:focus {
    border: 3px solid #555;
  }
  
input[type=submit] {
background-color: #04AA6D;
color: white;
padding: 20px;
border: none;
border-radius: 4px;
margin-top: 20px;
cursor: pointer;
float: right;
}

input[type=submit]:hover {
background-color: #45a049;
}

label {
padding: 12px 12px 12px 0;
display: inline-block;
}

ul {
  padding: 20px;
}

ul li {
  padding: 5px;
  margin-left: 35px;
}
</style>
{% if awards_list %}
    <ul>
    {% for award in awards_list %}
        <li>
            <a href="{% url 'awards:award_detail' award.id %}">{{ award.award_name }}</a>
            {% if award in user_voted_awards %}
                - &#x2611;
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No awards are available.</p>
{% endif %}
<form action="{% url 'awards:award_add' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Add new Award</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        
        <label for="award_name">Award name:</label><br>
        <input type="text" name="award_name" id="award_name" length="50" autocomplete="off" required />
    </fieldset>
    <input type="submit" value="Add">
</form>

dbesite/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

dbesite/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<style>
  a {
    text-decoration: underline;
    color: green;
    padding: 4px
  }
</style>
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
  <p><a href="{% url 'awards:index' %}">Awards Home</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}